version: "3.8"

services:
  ############################
  # PHP + Apache
  ############################
  app:
    build:
      context: "."
      args:
        uid: ${UID}
    container_name: ${APP_NAME}-app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - ./:/var/www/html
      - vendor:/var/www/html/vendor
    ports:
      - ${HTTP_PORT}:80
      #- 4431:443

  ############################
  # MYSQL database
  ############################
  mysql:
    image: ethantech/mysql:8.0
    container_name: ${APP_NAME}-mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql

  ############################
  # PHPMyadmin service
  ############################
  pma:
    container_name: ${APP_NAME}-pma
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80

  ############################
  # maildev service
  ############################
  maildev:
      container_name: ${APP_NAME}-maildev
      image: maildev/maildev
      ports:
          - "${MAILDEV_HTTP_PORT:-8082}:80"
          # - "${MAILDEV_SMTP_PORT:-8025}:25"

volumes:
  vendor:
  mysql: